### ISSUE TITLE
Quasar version

### ISSUE THREAD

**Issue by dbohdan** [atemerev/skynet#1]
It would be interesting to see a version of this benchmark implemented in Java/Scala/Kotlin using [Quasar](http://docs.paralleluniverse.co/quasar/).

**Comment by yogthos** [comment]
Would also be nice to see [Pulsar](http://docs.paralleluniverse.co/pulsar/) with Clojure.

**Comment by wizzard0** [comment]
PRs welcome.

**Comment by jolestar** [comment]
me too

**Comment by circlespainter** [comment]
Submitted PR #70 about Quasar (BTW there's an accompanying blog post [here](http://blog.paralleluniverse.co/2016/05/03/skynet-go-quasar/)).

**Comment by wizzard0** [comment]
Merged #70
