### ISSUE TITLE
The Haskell benchmark doesn't use the threaded runtime

### ISSUE THREAD

**Issue by bartavelle** [atemerev/skynet#17]
You have to compile with `-threaded`, and then run with `+RTS -N`.

Also is it really fair to use a `Chan` where an `MVar` would be just as nice?

**Comment by bartavelle** [comment]
This makes it a bit faster:

diff --git a/haskell/Skynet.hs b/haskell/Skynet.hs
index 80ea2ed..ad5ab72 100644
--- a/haskell/Skynet.hs
+++ b/haskell/Skynet.hs
@@ -1,27 +1,27 @@
 module Main (main) where
 
-import Control.Concurrent (forkIO)
-import Control.Concurrent.Chan (Chan, newChan, writeChan, readChan)
-import Control.Monad (forM_, replicateM)
+import Control.Concurrent
+import Control.Monad
 import Data.Time.Clock (getCurrentTime, diffUTCTime)
 
-skynet :: Chan Int -> Int -> Int -> Int -> IO ()
-skynet c num size div
-    | size == 1 = writeChan c num
+skynet :: MVar Int -> Int -> Int -> Int -> IO ()
+skynet c num size dv
+    | size == 1 = putMVar c num
     | otherwise = do
-          rc <- newChan
-          forM_ [0..div-1] $ \i -> do
+          mvars <- forM [0..dv-1] $ \i -> do
               let subNum  = num + i * sizeDiv
-                  sizeDiv = size `quot` div
-              forkIO $ skynet rc subNum sizeDiv div
-          sum <- sum <$> replicateM div (readChan rc)
-          writeChan c sum
+                  sizeDiv = size `quot` dv
+              rc <- newEmptyMVar
+              void $ forkIO $ skynet rc subNum sizeDiv dv
+              return rc
+          sm <- sum <$> mapM readMVar mvars
+          putMVar c sm
 
 main :: IO ()
 main = do
-    c      <- newChan
+    c      <- newEmptyMVar
     start  <- getCurrentTime
     _      <- forkIO $ skynet c 0 1000000 10
-    result <- readChan c
+    result <- readMVar c
     end    <- getCurrentTime
     putStrLn $ concat ["Result: ", show result, " in ", show (diffUTCTime end start)]

**Comment by bartavelle** [comment]
It's 15% faster with `MVar`s on my computer.

**Comment by osa1** [comment]
Makes sense, as channels are more general than what's needed here.

Results on my laptop: (first one is the `MVar` version)

```
➜  haskell git:(master) ✗ time (./Skynet2 +RTS -N4)                                  
Result: 499999500000 in 1.90832s
( ./Skynet2 +RTS -N4; )  6.39s user 1.64s system 329% cpu 2.433 total

➜  haskell git:(master) ✗ time (./Skynet +RTS -N4) 
Result: 499999500000 in 2.027485s
( ./Skynet +RTS -N4; )  6.92s user 1.38s system 356% cpu 2.327 total
```

**Comment by osa1** [comment]
Another interesting result is that `readMVar` is faster than `takeMVar`:

```
➜  haskell git:(master) ✗ ghc --make -O2 -fforce-recomp -rtsopts -threaded Skynet2.hs
[1 of 1] Compiling Main             ( Skynet2.hs, Skynet2.o )
Linking Skynet2 ...
➜  haskell git:(master) ✗ # takeMVar version
➜  haskell git:(master) ✗ time (./Skynet2 +RTS -N4)
Result: 499999500000 in 1.879891s
( ./Skynet2 +RTS -N4; )  6.04s user 1.59s system 360% cpu 2.118 total

➜  haskell git:(master) ✗ ghc --make -O2 -fforce-recomp -rtsopts -threaded Skynet2.hs
[1 of 1] Compiling Main             ( Skynet2.hs, Skynet2.o )
Linking Skynet2 ...
➜  haskell git:(master) ✗ # readMVar version
➜  haskell git:(master) ✗ time (./Skynet2 +RTS -N4)                                  
Result: 280600000000 in 1.739175s
( ./Skynet2 +RTS -N4; )  5.98s user 1.61s system 338% cpu 2.245 total
```

**Comment by bartavelle** [comment]
Also, I would have done this (even though we are not in the actor paradigm now) :

```
{-# LANGUAGE BangPatterns #-}
module Main (main) where

import Data.Time.Clock (getCurrentTime, diffUTCTime)

import Control.Parallel.Strategies

skynet :: Int -> Int -> Int -> Int
skynet num size dv
    | size == 1 = num
    | otherwise = sum (parMap rpar subcompute [0 .. dv-1])
    where
        subcompute i = let subNum  = num + i * sizeDiv
                           sizeDiv = size `quot` dv
                       in  skynet subNum sizeDiv dv
main :: IO ()
main = do
    start  <- getCurrentTime
    let !result = skynet 0 1000000 10
    end    <- getCurrentTime
    putStrLn $ concat ["Result: ", show result, " in ", show (diffUTCTime end start)]
```

And it is _much_ faster (0.027s on my computer).

**Comment by bitemyapp** [comment]
@bartavelle thank you for submitting these, I am going to PR this and other fixes!
